# Generated by Django 5.0.6 on 2024-09-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_class_name_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
