# Generated by Django 5.0.6 on 2024-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(db_column='birth_date'),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=50),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=50),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_column='student_id', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='studentid',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(db_column='class_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(db_column='gender', max_length=10),
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
