# Generated by Django 5.0.6 on 2024-09-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(db_column='BIRTHDATE'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(db_column='CLASS', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(db_column='FIRSTNAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(db_column='GENDER', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(db_column='LASTNAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(db_column='STUDENTID', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='student',
            table='"STUDENTS"',
        ),
    ]
