# Generated by Django 5.0.6 on 2024-09-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_birthdate_alter_student_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.AutoField(db_column='STUDENTID', primary_key=True, serialize=False),
        ),
    ]
