# Generated by Django 5.0.6 on 2024-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='teacherid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
