# Generated by Django 5.0.6 on 2024-09-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_rename_first_name_teacher_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_id',
            new_name='classid',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrollment_id',
            new_name='enrollmentid',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'cls')},
        ),
        migrations.AddField(
            model_name='class',
            name='classname',
            field=models.CharField(default='Default Class', max_length=100),
        ),
        migrations.AddField(
            model_name='class',
            name='teacherid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='school.teacher'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.class'),
        ),
        migrations.AlterModelTable(
            name='class',
            table='classes',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='class_name',
        ),
    ]
