# Generated by Django 5.0.6 on 2024-09-19 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_rename_class_id_class_classid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrollment_date',
            new_name='enrollmentdate',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='studentid',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('studentid', 'classid')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='cls',
        ),
    ]
