# Generated by Django 5.0.6 on 2024-09-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_enrollment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='classid',
            field=models.ForeignKey(db_column='CLASSID', on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentdate',
            field=models.DateField(db_column='ENROLLMENTDATE'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentid',
            field=models.AutoField(db_column='ENROLLMENTID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='studentid',
            field=models.ForeignKey(db_column='STUDENTID', on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='SCHOOL_ENROLLMENT',
        ),
    ]
