# Generated by Django 5.0.6 on 2024-09-19 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_enrollment_classid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='studentid',
            field=models.ForeignKey(db_column='<EXACT_COLUMN_NAME>', on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
    ]
