# Generated by Django 5.0.6 on 2024-09-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_date',
            new_name='attendancedate',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_id',
            new_name='attendanceid',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='class_name',
            new_name='classid',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='studentid',
        ),
        migrations.AlterField(
            model_name='class',
            name='classid',
            field=models.AutoField(db_column='CLASSID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='classname',
            field=models.CharField(db_column='CLASSNAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacherid',
            field=models.ForeignKey(db_column='TEACHERID', on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='studentid',
            field=models.ForeignKey(db_column='STUDENTID', on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('studentid', 'classid')},
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
        migrations.AlterModelTable(
            name='class',
            table='CLASSES',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='ENROLLMENTS',
        ),
    ]
