# Generated by Django 5.0.6 on 2024-09-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_rename_attendance_date_attendance_attendancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classid',
            field=models.ForeignKey(db_column='CLASSID', on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='studentid',
            field=models.ForeignKey(db_column='STUDENTID', on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
    ]
